### ISSUE TITLE
Error with some FASTA files

### ISSUE THREAD

**Issue by SophieS9** [alexcritschristoph/CircMG#1]
Hi Alex, 

I've just stumbled across this script as I'm looking for something to identify circular contigs from assemblies with viral data. Assemblies were done with spades. 11/12 worked fine, but one assembly produces the following error:

Removing old temp files
Importing contigs
Self-aligning contigs using lastz
Self-aligned contigs: 
Writing to files...
Traceback (most recent call last):
  File "find_circular.py", line 117, in <module>
    f.write(str(seqs[contig]) + "\n")
NameError: name 'contig' is not defined

I re-ran spades and the same error is still happening with the new fasta. 

My python knowledge isn't strong enough to work out the issue. Wondered if you'd take a look? The fasta is attached. 

Cheers! 

Sophie 

[contigs.fasta.zip](https://github.com/alexcritschristoph/VICA/files/210007/contigs.fasta.zip)

**Comment by alexcritschristoph** [comment]
Hi Sophie, 
Thanks for checking it out, I'm glad that this work could be of some help! I'll have a quick look and get back to you ASAP.
Thanks!
Alex

**Comment by alexcritschristoph** [comment]
Hi Sophie,
The latest update should fix this issue - this bug is because no circular contigs were found in that file with the settings you were using. By the way, when I tested your file with the default settings, I did find that one of the contigs was a possible hit:
NODE_6_length_42039_cov_23.1828_ID_204778
1   83  120 202 7841    +   +   83/83   100.0%  83

I'm working on publishing this work in the future, but in the meantime if you want to cite it, you can cite the publication: http://onlinelibrary.wiley.com/wol1/doi/10.1111/1462-2920.13259/abstract where these scripts were previously used.

Thanks!
Alex

**Comment by SophieS9** [comment]
Thanks Alex! Working now.

Will make sure to cite.

All the Best,

Sophie
